services:
  dbSmash:
    image: postgres
    environment:
      - POSTGRES_DB=smashBP
      - POSTGRES_USER=troyka
      - POSTGRES_PASSWORD=1914
    volumes:
      - datapg:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5500
    volumes:
      - .:/WORKDIR
    ports:
      - "5500:5500"
    depends_on:
      - dbSmash
volumes:
  datapg: {}